Refactor the repository layout
cisagov/skeleton-packer pull request #378
Opened 2024-10-10 19:07 UTC by mcdonnnj

#  #

## 🗣 Description ##

> [!NOTE]
> This is built on top of #376 because we need the updated version of [cisagov/pre-commit-packer].

This pull request reformats the repository layout including breaking the Packer template into multiple files.

## 💭 Motivation and context ##

With the `0.1.0` release of [cisagov/pre-commit-packer] we can now use Packer templates that consist of more than one file. This will make the template easier to maintain and modify. As part of that it made sense to treat Packer projects more like Terraform root modules since both Packer and Terraform are Hashicorp projects.

## 🧪 Testing ##

Automated tests pass.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] All new and existing tests pass.

[cisagov/pre-commit-packer]: https://github.com/cisagov/pre-commit-packer

2024-10-18 21:05 UTC, dv4harr10 approved these changes

2024-10-21 14:32 UTC, jsf9k requested changes

2024-10-21 14:32 UTC, jsf9k commented on README.md
> +that deploys to all regions by adding additional regions to the Packertemplate.
```suggestion
that deploys to all regions by adding additional regions to the Packer template.
```

2024-10-21 14:32 UTC, jsf9k commented on variables.pkr.hcl
Should we go ahead and add `nullable = false` for all these variables?

2024-10-21 17:47 UTC, dav3r approved these changes
👍 👍

2024-10-21 19:36 UTC, mcdonnnj commented on variables.pkr.hcl
I don't believe that is a valid [argument for Packer input variables](https://developer.hashicorp.com/packer/docs/templates/hcl_templates/variables#arguments). It's specifically something for Terraform modules as far as I can tell.

2024-10-29 13:28 UTC, jsf9k approved these changes

2024-12-10 13:58 UTC, merged