Add AMI build to build workflow
cisagov/skeleton-packer pull request #77
Opened 2021-07-09 14:55 UTC by jsf9k

## 🗣 Description ##

This pull request adds a `build` task to the `build` workflow.  This new task goes through the process of building a new AMI but does not actually register it.

This pull request is blocked until we move to Packer 1.7, since [that is where support for the `skip_create_ami` key was added for Packer configurations](https://github.com/hashicorp/packer/blob/master/CHANGELOG.md#improvements-3) (see the first bullet).

## 💭 Motivation and context ##

This is a useful feature to add since it will catch changes that cause the AMI build process to fail.  Currently these changes are only caught when we create a pre-release or release.

## 🧪 Testing ##

Hopefully all the tests will pass once we move to Packer 1.7! :crossed_fingers: 

## ✅ Checklist ##

* [x] This PR has an informative and human-readable title.
* [x] Changes are limited to a single goal - _eschew scope creep!_
* [x] All relevant type-of-change labels have been added.
* [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
* [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
* [x] Tests have been added and/or modified to cover the changes in this PR.
* [ ] All new and existing tests pass.

2021-07-12 17:12 UTC, felddy approved these changes
This is a good improvement.  It should catch a whole new class of errors.
Strong work. 💪

2021-07-13 17:19 UTC, dav3r approved these changes
Excellent! 🎸 
I only noted one small thang.

2021-07-13 17:19 UTC, dav3r commented on .github/workflows/build.yml
> +      - name: Install ansible roles
```suggestion
      - name: Install Ansible roles
```

2021-07-13 17:53 UTC, mcdonnnj requested changes
This is a great improvement. I have some suggestions that are mostly to bring this into alignment with the work in https://github.com/cisagov/skeleton-generic/pull/82.

2021-07-13 17:53 UTC, mcdonnnj commented on .github/workflows/build.yml
> +          sudo ln -s /opt/terraform/terraform /usr/bin/terraform
Mirroring the decision in https://github.com/cisagov/skeleton-generic/pull/82#discussion_r667214249

```suggestion
```

2021-07-13 17:53 UTC, mcdonnnj commented on .github/workflows/build.yml
> +            ${{ env.CURL_CACHE_DIR }}/"${PACKER_ZIP}"
Mirroring https://github.com/cisagov/skeleton-generic/pull/82#discussion_r667207173

```suggestion
          sudo unzip -d /opt/packer \
            ${{ env.CURL_CACHE_DIR }}/"${PACKER_ZIP}"
          sudo mv /usr/local/bin/packer /usr/local/bin/packer-default
          sudo ln -s /opt/packer/packer /usr/local/bin/packer
```

2021-07-13 17:53 UTC, mcdonnnj commented on .github/workflows/build.yml
> +      - name: Install ansible roles
```suggestion
      - name: Install Ansible roles
```

2021-07-13 17:53 UTC, mcdonnnj commented on .github/workflows/build.yml
> +      - name: Install Packer
Mirroring https://github.com/cisagov/skeleton-generic/pull/82/files#r667205518

```suggestion
      - name: Setup curl cache
        run: mkdir -p ${{ env.CURL_CACHE_DIR }}
      - name: Install Packer
```

2021-07-13 17:53 UTC, mcdonnnj commented on .github/workflows/build.yml
> +          mkdir -p ${{ env.CURL_CACHE_DIR }}
```suggestion
```

2021-07-13 20:06 UTC, jsf9k commented on .github/workflows/build.yml
> +      - name: Install ansible roles
See commit e95501d.

2021-07-14 07:35 UTC, mcdonnnj approved these changes
just some last suggestions. Thanks again for thinking of and implementing this improvement!

2021-07-14 07:35 UTC, mcdonnnj commented on .github/workflows/build.yml
> +      - test
This is how it's done in [the cisagov/skeleton-python-library build job](https://github.com/cisagov/skeleton-python-library/blob/4ef2364701c0db074c423f740062b2d7c197bea8/.github/workflows/build.yml#L113). I'm fine if we want to switch to this style, but I'd like to use the same format for similar functionality whichever way we decide.

```suggestion
    needs: [lint, test]
```

2021-07-14 07:35 UTC, mcdonnnj commented on .github/workflows/build.yml
> +      - name: Create a /usr/bin/python3 symlink to the installed python
```suggestion
      - name: Create a /usr/bin/python3 symlink to the installed Python
```

2021-07-14 07:35 UTC, mcdonnnj commented on .github/workflows/build.yml
> +      - name: Remove /usr/bin/python3 symlink to the installed python
```suggestion
      - name: Remove /usr/bin/python3 symlink to the installed Python
```

2021-07-22 20:09 UTC, merged